In [4]:
import torch
from tqdm.notebook import tqdm

from torch.utils.data import TensorDataset

from google.colab import drive
import pandas as pd

import nltk
import re
nltk.download('wordnet')
nltk.download('stopwords')
from nltk.corpus import stopwords
from  nltk.stem import SnowballStemmer

import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib as mpl

from sklearn.model_selection import train_test_split
from sklearn.utils import compute_class_weight

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

### Data Load

In [5]:
drive.mount('/content/drive')
path = '/content/drive/MyDrive/Memoria_Group_Classification/Datos/'
df = pd.read_csv(path + 'dataset_final.csv')
print(df.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(16570, 5)

In [6]:
df = df.drop_duplicates(subset=['text'])

In [7]:
df = df.drop(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0'], axis=1)
df.head()

,text,label
0,"level eight ab , a swedish corporation , with ...",policy_introductory
1,please note that your access and/or playing of...,policy_introductory
2,"where applicable , access and playing of certa...",first_party_collection_and_use
3,"however , in order to access and play the comp...",first_party_collection_and_use
4,you must then create an account on the game ’ ...,first_party_collection_and_use

### Encoded Label

In [8]:
possible_labels = df.label.unique()

label_dict = {}
for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index
label_dict

{'policy_introductory': 0,
 'first_party_collection_and_use': 1,
 'cookies_and_similar_technologies': 2,
 'data_retention': 3,
 'third_party_share_and_collection': 4,
 'data_security': 5,
 'international_data_transfer': 6,
 'user_right_and_control': 7,
 'specific_audiences': 8,
 'policy_change': 9,
 'policy_contact_information': 10}

In [9]:
df['clase'] = df.label.replace(label_dict)

### Split data

In [10]:
X, X_test, y, y_test = train_test_split(df.index.values,
                                        df.clase.values,
                                        test_size=0.10,
                                        random_state=42,
                                        stratify=df.clase.values)

X_train, X_val, y_train, y_val = train_test_split(X,
                                                  y,
                                                  test_size=0.10,
                                                  random_state=42,
                                                  stratify=y)

In [11]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(13229,)
(1470,)
(1634,)

In [12]:
df['data_type'] = ['not_set']*df.shape[0]

df.loc[X_train, 'data_type'] = 'train'
df.loc[X_val, 'data_type'] = 'val'
df.loc[X_test, 'data_type'] = 'test'

In [13]:
df.groupby(['label', 'clase', 'data_type']).count()

                                                  text
label                            clase data_type
cookies_and_similar_technologies 2     test        118
                                       train       954
                                       val         106
data_retention                   3     test         38
                                       train       310
                                       val          35
data_security                    5     test         82
                                       train       663
                                       val          74
first_party_collection_and_use   1     test        533
                                       train      4313
                                       val         479
international_data_transfer      6     test         40
                                       train       326
                                       val          36
policy_change                    9     test         52
                                       train       423
                                       val          47
policy_contact_information       10    test         46
                                       train       376
                                       val          42
policy_introductory              0     test        127
                                       train      1023
                                       val         114
specific_audiences               8     test         75
                                       train       604
                                       val          67
third_party_share_and_collection 4     test        286
                                       train      2316
                                       val         257
user_right_and_control           7     test        237
                                       train      1921
                                       val         213

In [14]:
from google.colab import files

df.to_csv('APP_CORP_SPLIT_DATA.csv', index=False)
files.download('APP_CORP_SPLIT_DATA.csv')