In [1]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.35.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.19.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2023.7.22)

In [2]:
!pip install spacy_fastlang

Collecting spacy_fastlang
  Downloading spacy_fastlang-2.0.0-py3-none-any.whl (780 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.4/780.4 kB 6.5 MB/s eta 0:00:00
Collecting fasttext-wheel<0.10.0,>=0.9.2 (from spacy_fastlang)
  Downloading fasttext_wheel-0.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 16.6 MB/s eta 0:00:00
Requirement already satisfied: spacy<4.0.0,>=3.6.0 in /usr/local/lib/python3.10/dist-packages (from spacy_fastlang) (3.6.1)
Collecting pybind11>=2.2 (from fasttext-wheel<0.10.0,>=0.9.2->spacy_fastlang)
  Downloading pybind11-2.11.1-py3-none-any.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.7/227.7 kB 20.1 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from fasttext-wheel<0.10.0,>=0.9.2->spacy_fastlang) (67.7.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from fasttext-wheel<0.10.0,>=0.9.2->spacy_fastlang) (1.23.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (3.0.9)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (8.1.12)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (2.0.10)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (0.9.0)
Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (0.10.3)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (4.66.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (1.10.13)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (3.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (23.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=3.6.0->spacy_fastlang) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.6.0->spacy_fastlang) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.6.0->spacy_fastlang) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.6.0->spacy_fastlang) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.6.0->spacy_fastlang) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.6.0->spacy_fastlang) (2023.7.22)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy<4.0.0,>=3.6.0->spacy_fastlang) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy<4.0.0,>=3.6.0->spacy_fastlang) (0.1.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy<4.0.0,>=3.6.0->spacy_fastlang) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<4.0.0,>=3.6.0->spacy_fastlang) (2.1.3)
Installing collected packages: pybind11, fasttext-wheel, spacy_fastlang
Successfully installed fasttext-wheel-0.9.2 pybind11-2.11.1 spacy_fastlang-2.0.0

In [3]:
import torch
from tqdm.notebook import tqdm

from transformers import BertTokenizer
from torch.utils.data import TensorDataset

from transformers import BertForSequenceClassification
import pandas as pd
import numpy as np

In [4]:
import random

seed_val = 17
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
path = '/content/drive/MyDrive/Memoria_Risk_Classification/Datasets/'

df_actual = pd.read_csv(path + 'Full_TOSDR_2023.csv')
df_actual['text'] = df_actual['text'].fillna(' ')

In [7]:
import spacy_fastlang
import spacy

nlp = spacy.load("en_core_web_sm")
nlp.add_pipe("language_detector")

def detect_lang(text):
  doc = nlp(text)
  return doc._.language

df_actual['idioma'] = df_actual['text'].apply(lambda x: detect_lang(x))

df_actual = df_actual[df_actual['idioma'] == 'en']
print(df_actual['idioma'].value_counts())

df = df_actual

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

en    4390
Name: idioma, dtype: int64

In [8]:
label_map = {
    'success': 0,
    'secondary': 0,
    'warning' : 1,
    'danger': 1,
}

df['label'] = df['label'].map(label_map)
print(df.shape)
df.head(3)

(4390, 7)

,Unnamed: 0,service,privacy_text,case_link,label,text,idioma
0,0,1password,The service does not guarantee that software e...,https://edit.tosdr.org/points/6727,1,any errors or defects will be corrected\r\nTer...,en
1,1,1password,This service provides archives of their terms ...,https://edit.tosdr.org/points/6728,0,The Change Log section below is not a part of ...,en
2,2,1password,The services will notify users if personal dat...,https://edit.tosdr.org/points/13405,0,"<p>In an event of a breach, we recognize our r...",en

In [9]:
df['label'].value_counts()

0    2861
1    1529
Name: label, dtype: int64

In [10]:
print(df.head())
print(df.shape)

   Unnamed: 0    service                                       privacy_text  \
0           0  1password  The service does not guarantee that software e...
1           1  1password  This service provides archives of their terms ...
2           2  1password  The services will notify users if personal dat...
3           3  1password  This service assumes no liability for any loss...
4           4  1password  Users should revisit the terms periodically, a...

                             case_link  label  \
0   https://edit.tosdr.org/points/6727      1
1   https://edit.tosdr.org/points/6728      0
2  https://edit.tosdr.org/points/13405      0
3   https://edit.tosdr.org/points/6724      0
4   https://edit.tosdr.org/points/6723      0

                                                text idioma
0  any errors or defects will be corrected\r\nTer...     en
1  The Change Log section below is not a part of ...     en
2  <p>In an event of a breach, we recognize our r...     en
3  AgileBits, Inc., its directors, employees, par...     en
4  At our discretion, we may make changes to this...     en
(4390, 7)

In [11]:
df['label'].value_counts()

0    2861
1    1529
Name: label, dtype: int64

In [12]:
import re

def clean_text(texto):
    texto = re.sub(r'<.*?>', ' ', texto)
    texto = re.sub(r'[\n\r\t]', ' ', texto)
    return texto

df['text'] = df['text'].map(clean_text)
df.head(3)

,Unnamed: 0,service,privacy_text,case_link,label,text,idioma
0,0,1password,The service does not guarantee that software e...,https://edit.tosdr.org/points/6727,1,any errors or defects will be corrected Terms...,en
1,1,1password,This service provides archives of their terms ...,https://edit.tosdr.org/points/6728,0,The Change Log section below is not a part of ...,en
2,2,1password,The services will notify users if personal dat...,https://edit.tosdr.org/points/13405,0,"In an event of a breach, we recognize our res...",en

In [13]:
df['clase'] = df['label']

In [14]:
df.head()

,Unnamed: 0,service,privacy_text,case_link,label,text,idioma,clase
0,0,1password,The service does not guarantee that software e...,https://edit.tosdr.org/points/6727,1,any errors or defects will be corrected Terms...,en,1
1,1,1password,This service provides archives of their terms ...,https://edit.tosdr.org/points/6728,0,The Change Log section below is not a part of ...,en,0
2,2,1password,The services will notify users if personal dat...,https://edit.tosdr.org/points/13405,0,"In an event of a breach, we recognize our res...",en,0
3,3,1password,This service assumes no liability for any loss...,https://edit.tosdr.org/points/6724,0,"AgileBits, Inc., its directors, employees, par...",en,0
4,4,1password,"Users should revisit the terms periodically, a...",https://edit.tosdr.org/points/6723,0,"At our discretion, we may make changes to this...",en,0

In [15]:
from sklearn.model_selection import train_test_split

X, X_test, y, y_test = train_test_split(df.index.values,
                                        df.clase.values,
                                        test_size=0.10,
                                        random_state=42,
                                        stratify=df.clase.values)

X_train, X_val, y_train, y_val = train_test_split(X,
                                                  y,
                                                  test_size=0.10,
                                                  random_state=42,
                                                  stratify=y)

In [16]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(3555,)
(396,)
(439,)

In [17]:
df['data_type'] = ['not_set']*df.shape[0]

df.loc[X_train, 'data_type'] = 'train'
df.loc[X_val, 'data_type'] = 'val'
df.loc[X_test, 'data_type'] = 'test'

In [18]:
df.groupby(['clase', 'data_type']).count()

                 Unnamed: 0  service  privacy_text  case_link  label  text  \
clase data_type
0     test              286      286           286        286    286   286
      train            2317     2317          2317       2317   2317  2317
      val               258      258           258        258    258   258
1     test              153      153           153        153    153   153
      train            1238     1238          1238       1238   1238  1238
      val               138      138           138        138    138   138

                 idioma
clase data_type
0     test          286
      train        2317
      val           258
1     test          153
      train        1238
      val           138

In [19]:
from google.colab import files

df.to_csv('TOSDR_SPLIT_DATA.csv', index=False)
files.download('TOSDR_SPLIT_DATA.csv')